Lucien
bClemot-Sc/MODE_reproduciblescience_bootstrapping pull request #14
Opened 2023-12-08 14:28 UTC by LucienRicome

add regression & mantel test part

2023-12-08 16:09 UTC, YounaDcht requested changes
bon courage, j'ai mis quelques commentaires, mais le bilan global c'est plutôt qu'il faudrait que tu essayes d'expliquer plus avec des petits textes (à la manière de Bastien)
explicite bien les sorties de tes fonctions R avec les sorties une par une et à quoi elles correspondent dans ta partie théorique

2023-12-08 16:09 UTC, YounaDcht commented on r_chapter_boostrapping_resampling.qmd
> +Regression is a method of empirically modeling a response variable (here called $Y$) as a function of one or more explanatory variables ( $X_1,X_2,.,X_n$ where $n$ is the number of explanatory variab
The linear model is classically expressed as follow

2023-12-08 16:09 UTC, YounaDcht commented on r_chapter_boostrapping_resampling.qmd
> +We now need to make sure that the parameters \$b\$ and $\alpha$ are different from 0. The permutation test is used to define the null hypothesis (H0: $\alpha=0$ and $b = 0$). The idea is to permute t
phrase en français pour H0 
le début de ce paragraphe est un peu brutal, on pourrait introduire sur pourquoi on veut savoir si les coefficients sont différents de 0

2023-12-08 16:09 UTC, YounaDcht commented on r_chapter_boostrapping_resampling.qmd
> +
pour le tableau que tu présente, ce n'est pas clair que tu montres deux fois le même échantillon mais avec sample
peut etre que tu peux changer les titres des colonnes

2023-12-08 16:09 UTC, YounaDcht commented on r_chapter_boostrapping_resampling.qmd
> +So, you can obtain the significances of your coefficients with the exacts p values.
retirer le 'So'

2023-12-08 16:09 UTC, YounaDcht commented on r_chapter_boostrapping_resampling.qmd
> +So, you can obtain the significances of your coefficients with the exacts p values.
utiliser plutot we

2023-12-12 13:20 UTC, LucienRicome commented
Merge post réglages et gestion du conflit

2023-12-12 13:21 UTC, merged